Ovo je gdje ja živim . Živim u Keniji , u južnim dijelovima Nacionalnog parka Nairobi .
Iza su krave mog oca , a iza krava , to je Nacionalni park Nairobi .
Nacionalni park Nairobi nije ograđen širom jednog dijela na jugu , što znači da divlje životinje poput zebri slobodno mogu izaći iz parka .
Grabežjivci poput lavova prate ih , i evo šta rade .
Ubijaju našu stoku .
Ovo je jedna od krava koja je ubijena u noći , i kad sam se probudio ujutru i našao je mrtvu , osjećao sam se loše , jer je to bio jedini vol kojeg smo imali .
Moja zajednica , Maasai , mi vjerujemo da smo stigli iz raja sa svim našim životinjama i svom našom zemljom , da bi ih uzgajali , i upravo zbog toga ih jako cijenimo .
Zato sam odrastao mrzeći lavove toliko .
Morani su ratnici , koji štite svoju zajednicu i stoku , i oni su također uznemireni zbog ovog problema .
Zato ubijaju lavove .
Ovo je jedan od šest lavova koji su ubijeni u Nairobiju .
Mislim da zbog toga ima jako malo lavova u Nacionalnom parku Nairobi .
Dječak , od šest do devet godina , u mojoj zajednici , odgovoran je za krave svog oca , i isto se desilo i meni .
Zbog toga sam morao pronaći način da riješim ovaj problem .
Prva ideja koju sam imao bila je da upotrijebim vatru , zato što sam mislio da se lavovi boje vatre .
Ali ubrzo sam shvatio da to neće puno pomoći , zato što je to čak pomagalo lavovima da vide kroz staje .
Nisam odustajao . Nastavio sam .
Sljedeća ideja koju sam imao jeste da upotrijebim strašilo .
Pokušao sam da prevarim lavove kao da ja stojim blizu staje .
Ali lavovi su vrlo pametni . ( smijeh ) Doći će prvog dana i vidjet će strašilo , i otići će , ali drugog dana , vratit će se opet i reći će da se ova stvar ne miče odavde , uvijek je tu . ( Smijeh ) Tada skoči i ubije životinje .
Jedne noći , šetao sam oko staje s bakljom , i tog dana , lavovi nisu došli .
Otkrio sam da se lavovi plaše pokretnog svjetla .
I nadošao sam na ideju .
S obzirom da sam bio mali dječak , imao sam običaj da radim u svojoj sobi po cio dan , i jednom sam čak razmontirao mamin novi radio , i tog dana samo što me nije ubila , ali sam mnogo naučio o elektronici . ( Smijeh ) Nabavio sam staru automobilsku bateriju , indikatorsku kutiju . To je malena naprava koja se može naći u motorciklima , i pomaže motoristima ukoliko žele da se vrate unazad desno ili lijevo . Svjetluca .
Dobio sam prekidač na kojem svijetlo mogu paliti i gasiti .
I to je malena baklja iz razbijene svjetiljke .
Tako sam namjestio sve .
Kao što vidite , solarni panel puni bateriju , i baterija isporučuje energiju u malu indikatorsku kutiju . Ja to zovem transformator .
Indikatorska kutija čini da svijetlo bljeska .
Kao što vidite , žarulja su okrenute prema van , zato što odatle dolaze lavovi .
I tako to izgleda lavovima kada dolaze u noći .
Svijetlo treperi i vara lavove da misle kako se krećem oko staje , ali ja spavam u svom krevetu .
( Smijeh ) ( Aplauz ) Hvala .
Namjestio sam to u svom domu prije dvije godine , i od tada , nismo imali nikakvih problema s lavovima .
I moje komšije su čule za ovu ideju .
Jedna od njih bila je ova baka .
Veliki broj njenih životinja pobili su lavovi , i pitala me da li mogu za nju da postavim svijetla .
Rekao sam : &quot; &quot; Da &quot; &quot; . Postavio sam svijetla . Kao što vidite u pozadini , to su svijetla za lavove .
Do sada , postavio sam ih na sedam kuća unutar moje zajednice , i zaista rade .
Moja ideja sada se koristi u cijeloj Keniji kako bi se otjerali drugi grabljivci poput hijena , leoparda , i također se koristi kako bi se otjerali slonovi što dalje od farmi .
Zahvaljujući ovom izumu , imao sam sreću da dobijem stipendiju u jednoj od najboljih škola u Keniji , Međunarodnoj školi Brookhouse i zaista sam uzbuđen zbog toga .
Moja nova škola sada pomaže pri prikupljanju sredstava i stvaranju svijesti .
Čak sam odveo svoje prijatelje u svoju zajednicu , i postavljamo svijetla na kuće koje ga nemaju nikako , i učim ih kako da ga postave .
Prije godinu dana , bio sam tek dječak iz savane koji je uzgajao očeve krave , i obično sam posmatrao kako avioni lete preko , i rekao sam samome sebi da ću jednog dana ja biti u njemu ,
i evo me danas .
Dobio sam priliku da stignem avionom po prvi put na TED .
Moj veliki san kad odrastem jeste da postanem inženjer zrakoplovstva i pilot .
Imao sam običaj da mrzim lavove , ali danas zato što moj izum spašava očeve krave i lavove , u stanju smo biti pokraj lavova bez ikakvih sukoba .
Ashe olen . Na mom jeziku to znači hvala vam mnogo .
( Aplauz ) Chris Anderson : &quot; &quot; Nemaš pojma kako je uzbudljivo čuti priču poput tvoje .
Znači dobio si stipendiju . &quot; &quot; Richard Turere : &quot; &quot; Da . &quot; &quot;
CA : &quot; &quot; Radiš na nekim drugim elektronskim izumima .
Šta je sljedeće na tvojoj listi ? &quot; &quot;
RT : &quot; &quot; Moj sljedeći izum je ... želim da napravim električnu ogradu . &quot; &quot; CA : &quot; &quot; Električnu ogradu ? &quot; &quot;
RT : &quot; &quot; Ali znam da su električne ograde već izumljene , ali ja želim da napravim svoju . &quot; &quot;
( Smijeh ) CA : &quot; &quot; Već si pokušao jednom , zar ne , i ti ... &quot; &quot; RT : &quot; &quot; Pokušao sam već ranije , ali sam prekinuo jer me udarila struja . &quot; &quot; ( Smijeh ) CA : &quot; &quot; U rovovima . Richard Turere , ti si zaista nešto .
Bodrit ćemo te na svakom koraku , moj prijatelju .
Hvala ti puno . &quot; &quot; RT : &quot; &quot; Hvala . &quot; &quot; ( Aplauz )
Sa sedam godina sam prvi put vidjela javno pogubljenje ,
Nisam imala pojma kakav će mi biti život kao izbjeglice iz Sjeverne Koreje
Ako se nešto učini neprirodnim , mogla bih biti zarobljena
Iako sam imala veliku sreću da se izvučem , brojni Sjevernokorejci nisu bili te sreće .
Čak i nakon što nauče jezik i dobiju posao , njihov cijeli svijet može biti prevrnut u sekundi .
Svi smo Korejci , ali iznutra smo postali jako različiti
Jesam li Sjeverno-korejanka ili Južno-korejanka ?
pa sam počela planirati kako da im pomognem da pobjegnu .
Bila sam iznenađena
Shvatila sam da je to simboličan trenutak u mom životu .
( Muzika ) ( Aplauz )
Evo nekoliko slika skupina galaksija .
I one su upravo to .
One su ogromni zbirovi galaksija , povezani zajedničkom gravitacijom .
Većina tačaka koje vidite na ekranu nisu pojedinačne zvijezde , već zbirovi zvijezda ili galaksija .
Pokazujući vam neke od ovih slika , nadam se da ćete brzo uvidjeti da su zbirovi galaksija ovi prelijepi objekti , ali i više od toga . Lično mislim da su skupine sazviježđa misteriozne , da su iznenađujuće i da su korisne .
Korisne kao najveće laboratorije univerzuma .
I kao kada opisujete laboratorije , opisati skupine galaksija znači opisati eksperimente koje s njima možete raditi .
A ja mislim da postoje četiri glavne vrste eksperimenata , a prva vrsta koju želim da opišem je ispitivanje jako velikog .
Koliko velikog ?
Evo slike određene skupine galaksija .
Ova je skupina toliko velika da se svjetlo koje kroz nju prolazi savija , deformira zbog ekstremne gravitacije ovog zbira sazviježđa .
I , zapravo , ako dobro pogledate vidjet ćete prstenove oko ove skupine .
Da biste dobili predstavu , ova konkretna skupina galaksija ima masu veću od jednog miliona milijardi sunaca .
Jednostavno je nepojmljivo koliko mogu biti veliki ovi sistemi .
Ali , važnija od njihove mase je njihova dodatna osobina .
One su u osnovi izolovani sistemi , tako da , ako želimo , o njima možemo razmišljati kao o umanjenim verzijama cijelog svemira .
Mnoga pitanja koja možda imamo o svemiru , u širem smislu , kao na primjer &quot; &quot; kako djeluje gravitacija ? &quot; &quot;
mogu biti odgovorena proučavanjem ovih sistema .
To je , dakle , jako veliko .
Druga stvar je - vrelo .
Ako uzmem sliku skupine galaksija i s nje uklonim svjetlost zvijezda ostaje mi ova velika , plava mrlja .
Ovo nije prava boja .
Ovo što vidimo je zapravo svjetlo rendgenskog zraka .
Sada je pitanje , ako to nisu galaksije , šta onda emituje ovu svjetlost ?
Odgovor je vreli gas , gas od milion stepeni - zapravo , to je plazma .
A razlog zašto je tako vrelo je na prethodnom slajdu .
Ekstremna gravitacija ovih sistema ubrzava čestice gasa do velikih brzina , a velike brzine znače i velike temperature .
Ovo je , dakle , osnovna ideja , ali nauka je grubi nacrt .
Mnoge osnovne osobine plazme nas još uvijek zbunjuju , tjeraju na razmišljanje i pomijeraju granice našeg razumijevanja fizike vrelog .
Treća stvar : ispitivanje jako malog .
Da bih vam ovo objasnio , moram vam reći vrlo uznemirujuću činjenicu .
Najveći dio materije svemira nije sačinjen od atoma .
Lagali su vam .
Najveći dio je sačinjen od nečeg jako , jako misterioznog , što se zove tamna materija .
Tamna materija je nešto što ne voli interakciju , osim kroz gravitaciju , i , naravno , želimo znati više o njoj .
Ako se bavite fizikom čestica , želite znati šta se dešava kada sudarimo dvije stvari .
A tamna materija nije izuzetak .
I kako onda to radimo ?
Da bih odgovorio na to pitanje moram postaviti drugo , a to je &quot; &quot; šta se dešava kada se sudare dvije skupine galaksija ? &quot; &quot;
Evo slike .
Skupine galaksija predstavljaju isječke univerzuma , njegove umanjene verzije .
Sačinjene su uglavnom od tamne materije , i to je ono što vidite u plavo-ljubičastoj boji .
Crvena predstavlja vreli gas , i naravno , vidite mnogo galaksija .
Ono što se desilo je ubrzivač čestica na ogromnom , ogromnom nivou .
Ovo je jako važno jer znači da bi se jako , jako mali efekti koje bi bilo teško detektovati u laboratoriji mogli jediniti i jediniti u nešto što bismo mogli primijetiti u prirodi .
Smiješno je .
Razlog zašto preko skupine galaksija možemo učiti o tamnoj materiji , razlog zašto kroz skupine galaksija možemo učiti o fizici jako malog , je upravo zato što su tako velike .
Četvrta stvar : fizika jako neobičnog .
Naravno da je sve što sam do sada rekao ludo .
Uredu , ako postoji išta neobičnije mislim da to onda mora biti tamna energija .
Ako bacim loptu u zrak , očekujem da će ići gore .
Ono što ne očekujem je da ide gore sve brže i brže .
Slično tome , kozmolozi razumiju zašto se svemir širi .
Ne razumiju zašto se širi sve brže i brže .
Razlog ovog ubrzanog širenja ima ime , i zovu ga tamna energija .
I opet želimo znati više o njoj .
Jedno određeno pitanje koje imamo je kako tamna energija utječe na svemir na većem planu ?
Zavisno od toga koliko je jaka , možda se strukture formiraju brže ili sporije .
Problem sa velikom strukturom svemira je taj što je užasno komplikovana .
Pogledajte kompjutersku simulaciju .
Potreban nam je način da je pojednostavimo .
O ovome volim razmišljati koristeći analogiju .
Ako želim razumjeti kako je potonuo Titanik nije najvažnije tačno postaviti svaki djelić koji se odvojio s broda .
Najvažnije je pronaći dva najveća dijela .
Na sličan način mogu mnogo naučiti o svemiru na širem planu prateći njegove najveće dijelove , a najveći dijelovi su skupine galaksija .
Kako se bližim završetku možda se osjećate malo prevarenima .
Mislim , počeo sam govorom o tome kako su skupine galaksija korisne i naveo sam neke razloge , ali koja je njihova stvarna korist ?
Da bih odgovorio na ovo , želim citirati Henrya Forda kada su ga pitali o autima .
On je rekao ovo : &quot; &quot; Da sam pitao ljude šta žele , tražili bi brže konje &quot; &quot; . Danas smo kao društvo suočeni sa jako mnogo teških problema .
A rješenja ovih problema nisu očigledna .
Ona nisu &quot; &quot; brži konji &quot; &quot; .
Ta će rješenja zahtijevati ogromnu količinu naučne genijalnosti .
Dakle , da , moramo se fokusirati , da , moramo se koncentrisati , Ali isto tako moramo upamtiti da inovacija , genijalnost , inspiracija - ove stvari dolaze kada proširimo svoje vidike , kada zakoračimo unazad , kada sagledamo veću sliku .
A ja ne mogu da zamislim bolji način da se ovo uradi nego posmatranjem svemira oko nas . Hvala .
Aplauz
Mogu li vas geografske informacije načiniti zdravim ?
2001. mene je udario voz .
Moj voz je bio srčani udar .
Našao sam se u bolnici na odjelu intenzivne njege , oporavljajući se od hitne operacije .
I iznenada sam shvatio : bio sam u potpunosti neinformisan .
Počeo sam postavljati svoja pitanja , &apos; &apos; Pa , zašto ja ? &apos; &apos; &apos; &apos; Zašto sada ? &apos; &apos; &apos; &apos; Zašto ovdje ? &apos; &apos;
&apos; &apos; Da li me je moj doktor mogao upozoriti ? &apos; &apos;
Zato , ono što ja želim uraditi u par minuta koje imam sa vama jeste da govorim o formuli za život i dobro zdravlje .
Genetika , stil življenja i okruženje .
U njima će se , na neki način , sadržavati naši rizici i ako mi kontrolišemo te rizike imat ćemo dobar i veoma zdrav život .
Naime , ja se razumijem u dio koji se odnosi na genetiku i način življenja .
I znate li zašto se u to razumijem ?
Zato što su mi moji doktori konstantno postavljali pitanja o tome .
Da li ste ikada morali popopunjavati one duge formulare , veličine zakonskih formulara , u ordinaciji vašeg doktora ?
Milsim , ako ste dovoljno sretni taj će te proces ponoviti više puta , zar ne ?
( Smijeh ) Popunite ih nekoliko puta . I oni vas pitaju o vašem načinu življenja i porodičnoj istoriji , o vašoj istoriji konzumiranja lijekova , vašoj istoriji operacija , vašoj istoriji alergija ... da li sam zaboravio neku istoriju ?
Ali ovaj dio jednačine ni ja nisam u potpunosti shvatio . I mislim da ni moji doktori ustvari ne razumiju ovaj dio jednačine .
Šta to znači , moje okruženje ?
Pa , to može značiti mnogo toga .
Ovo je moj život . Ovo su moja mjesta u životu .
Mi ih svi imamo .
Dok ja pričam , želio bih da i vi također razmišljate o broju mjesta u kojima ste boravili .
Samo mislite o tome , hoću reći , lutajte kroz svoj život razmišljajući o ovome .
I shvatiti ćete da ste ga proveli na raznim i različitim mjestima .
Proveli ste ga u odmaranju i na poslu .
I ako ste poput mene , dobar dio svog vremena provodite u avionu putujući negdje .
Tako da to nije uopšte toliko jednostavno kada vas neko pita , &apos; &apos; Gdje živite , gdje radite , i gdje provodite svo vaše vrijeme ?
I gdje se izlažete rizicima koje možda i ne vidite ? &apos; &apos; Pa , kada sam ja ovo uradio na sebi , uvijek sam dolazio do zaključka da provodim oko 75 posto svog vremena na relativno malom broju mjesta .
I ne lutam daleko od tog mjesta veći dio svog vremena , iako sam veoma globalno prostran putnik .
Sada ću vas povesti na malo putovanje .
Ja sam počeo u Skrentonu , u Pensilvaniji
Ne znam da li možda neko dolazi iz sjeverno-istočne Pensilvanije . Ali ovdje sam proveo svojih prvih 19 godina sa svojim malim i mladim plućima .
Znate , udišući velike koncentracije sulfor dioksida , karbon dioksida i metan gasa , u nejednakim količinama - 19 godina ovoga .
I ako ste bili u tom dijelu države , ovo je kako te gomile sagorjevajućeg , tinjajućeg otpada uglja izgledaju .
Tako da sam tada odlučio napustiti taj dio svijeta . I planirao sam otići na srednji-zapad .
Uredu , i tako sam završio u Luivilu , u Kentakiju .
Onda sam odlučio biti susjed sa mjestom zvanim Rabertaun .
Oni proizvode plastiku . Koriste velike količine kloroprena i benzena .
Uredu , proveo sam 25 godina , sa svojim plućima sada srednjih godina udišući razne koncentracije toga .
I na vedar dan uvijek je izgledalo ovako , tako da to nikad niste vidjeli .
To je bilo podmuklo i zaista se događalo .
I onda sam odlučio da moram postati veoma pametan , i da ću prihvatiti ovaj posao na zapadnoj obali .
Tako sam se preselio u Redlands u Kaliforniji .
Veoma fino , i tamo sam moja starija , seniorska pluća , kako ih ja volim zvati , napunio česticama supstanci , karbon dioksidom i veoma visokim količinama ozona .
U redu ? Skoro sa najvećim nivoom u naciji .
Eh sada , ovako ono izgleda na dobar dan .
Ako ste bili tamo onda znate o čemu govorim .
Prema tome , šta nije uredu sa ovom slikom ?
Pa , slika je , ovdje ima velika praznina .
Jedna stvar koja se nikada ne događa u kancelariji mog doktora je : nikada me ne pitaju o istoriji mojih mjesta boravka .
Niti jedan doktor , koliko se mogu sjetiti , me nije pitao &apos; &apos; Gdje ste živjeli ? &apos; &apos;
Nisu me pitali o kvalitetu pitke vode koju stavljam u svoja usta , ili hrane koju unosim u stomak .
Oni to stvarno ne rade . To nedostaje .
Pogledajte vrste podataka koje su dostupne .
Ovi podaci su iz svih dijelova svijeta - zemlje troše milijarde dolara ulažući ih u ove vrste istraživanja .
Ja sam zaokružio mjesta gdje sam bio .
Tako da , prema dizajnu , ako sam želio da imam srčani udar onda sam bio na pravim mjestima . Zar ne ?
Prema tome , koliko ljudi je u bijelom ?
Koliko ljudi u prostoriji su proveli veći dio svojih života u bijelim mjestima ?
Iko ? Kako ste samo sretni .
Koliko vas je provelo vremena u crvenim mjestima ?
Oh , ne baš toliko sretni .
Postoje hiljade ovakvih karti koje su prikazane u atlasima po cijelom svijetu .
Oni nam daju neki smisao o tome šta će biti naš sudar sa vozom .
Ali ništa od toga nije u mom medicinskom kartonu .
I nije ni u vašem .
Ovo je moj prijatelj Pol .
On je moj kolega . On je dozvolio da mu prate mobilni telefon svaka dva sata , 24 sata u sedmici , 365 dana u godini , u posljednje dvije godine , gdje god da je išao .
I možete vidjeti da je bio na nekoliko mjesta po cijelim Ujedinjenim Državama .
I ovdje je provodio veći dio svog vremena .
Ako to usitinu prostudirate možda će te shvatiti šta to Pol voli raditi .
Da li iko ima neku ideju ? Skijanje . Tako je .
Možemo ovdje zumirati , i iznenada uviđamo da sada primjećujemo gdje je Pol zaista provodio veći dio svog vremena .
I sve te crne tačke su mjesta oslobađanja toksičkih zaliha koje nadgleda EPA ( Agencija za Zaštitu Okoline ) .
Jeste li znali da ti podaci postoje ?
Za svaku zajednicu u Sjedinjenim Američkim Državama , mogli biste imati istu , ali svoju ličnu mapu .
Tako da sada , naši mobilni telefoni , mogu izgraditi mjesto u istoriji .
Ovo je način na koji je to Pol uradio . On je to izvršio sa svojim iPhone-om .
Ovo može biti ono s čime ćemo završiti .
Ovo je ono što će doktori imati ispred sebe kada uđemo u tu ordinaciju umjesto same otpusnice koja govori kako smo platili na šalteru . Zar ne ?
Ovo bi mogla biti moja mala procjena .
I on pogleda u to i kaže , &apos; &apos; Uh Bil , ja predlažem da možda ne odlučuješ , samo zbog toga što si ovdje u prelijepoj Kaliforniji i zbog toga što je toplo svakog dana da izađeš trčati u šest sati navečer .
Ja to smatram kao lošu ideju Bil , uzimajući u obzir ovaj izvještaj . &apos; &apos; Ono s čime bih ja vas htio ostaviti su dva recepta .
Ok , broj jedan je taj da moramo naučiti doktore o vrijednosti geografskih informacija .
To se zove geomedicina . Trenutno postoji otprilike šest programa u svijetu koji su fokusirani na ovo .
I oni se nalaze u ranim fazama razvoja .
Ovi programi moraju biti podržani . I mi moramo naučiti naše buduće doktore svijeta važnosti nekih informacija koje sam podijelio ovdje s vama danas .
Druga stvar koju moramo uraditi jeste da , dok trošimo milijarde i milijarde dolara po cijelom svijetu na izradu elektonskih zdravstvenih podataka , mi moramo da stavimo istoriju mjesta boravka unutar naših zdravstvenih podataka .
To neće biti bitno samo za doktore ; to će biti bitno za istraživače koji će sada imati mnoštvo uzoraka koje mogu iskoristiti .
Ali to će također biti korisno za nas .
Mogao sam donijeti odluku , da sam imao ovu informaciju , da se ne preselim u glavni ozonski grad Sjedinjenih Američkih Država . Zar nisam ? Mogao sam donijeti tu odluku .
Ili sam mogao pregovarati sa svojim uposlenikom da donesem odluku koja je u mom najboljem interesu kao i interesu same kompanije .
Sa time , volio bih dodati kako je Džek Lord ovo rekao prije skoro 10 godina .
Samo pogledajte to na trenutak .
To je bio zaključak samog Dartmut Atlas-a Zdravstvene skrbi , gdje su takođe govorili kako možemo objasniti geografske varijacije koje se pojavljuju u bolestima , oboljenjima , zdravlju , i kako naš sistem zdravstvene skrbi , ustvari , funkcioniše .
On je o tome pričao u tom citatu .
I mogu reći da je pogodio i to skoro prije 10 godina .
Tako da bih ja volio veoma mnogo da mi ovo vidimo kao našu priliku kako bi te podatke uvrstili u naš zdravstveni karton .
Prema tome , ja ću vas ostaviti sa tezom da je , po mom ličnom mišljenju o zdravlju , geografija uvijek bitna .
I ja vjerujem da geografske informacije mogu vas kao i mene načiniti veoma zdravim . Hvala vam .
( Aplauz )
( Aplauz ) Jedan od stvarnih izazova
Ali , vidite , postoje stvari u obrazovanju za koje smo vezani .
Ovaj jedan profesor me nije uzimao zaozbiljno .
Ne kaže vam ni riječi - samo ode s njom .
Ne kaže vam razlog zbog čega je uzeo baš vašu stolicu od toliko drugih .
Nije ga briga da li vi trebate stolicu da obavite današnji posao .
Vi to ne bi trpjeli , nego bi napravili frku .
Pratili biste tog kolegu do njegovog stola i upitali ga &quot; &quot; Zašto moja stolica ? &quot; &quot; . Utorak je , nalazite se u svom uredu i dobijate pozivnicu u vašem kalendaru .
( Smijeh ) Pozivnica je od kolegice koju poznajete i radi se o projektu o kojem ste čuli .
Ali ne sadrži nikakav dnevni red .
Nema informacija o tome zašto ste baš vi pozvani na sastanak .
Ali ipak prihvatite pozivnicu i odlazite .
I govorim o stvarima koje su veće vrijednosti nego kancelarijski namještaj .
Govorim o vremenu . Vašem vremenu .
Ustvari vjerujem , da smo usred globalne epidemije poznate kao BPS : Bezumni Prihvatajući Sindrom .
( Smijeh ) Primarni simptom BPS je prihvatanje pozivnice za sastanak čim se ona pojavi na vašem kalendaru . ( Smijeh )
To je nenamjerni refleks kojim prihvatate da sudjelujete na sastanku , &quot; &quot; Moram ići , zakasnio sam na sastanak . &quot; &quot; ( Smijeh ) Sastanci su važni , zar ne ?
Kolaboracija je ključ uspjeha bilo koje organizacije .
A dobar sastanak može rezultirati pozitivnim rezultatima .
Globalizacija i informacione tehnologije promjenili su način na koji mi radimo .
Osjećamo se nesretno . ( Smijeh ) Razlog našeg osjećanja nije kolega koji ne zna da vodi dobar sastanak . Razlog je sindrom BPS , rana koju smo sami sebi nanijeli .
Imam dokaze da je BPS globalna epidemija .
Reći ću vam zašto .
Prije par godina postavio sam video na Youtube-u , u kojem sam odglumio konferencijski poziv na najgori mogući način .
Poziv je trajao oko 5 minuta . To su one stvari koje mrzimo na sastancima .
Tu je moderator koji ne zna da vodi sastanak ,
sudionici , koji ne znaju zbog čega su tu ,
sastanak , gdje sudionici nisu produktivni
U neku ruku je i smiješno .
( Smijeh ) Pogledajmo .
( Video ) Naš cilj danas jeste da dođemo do važnog dogovora .
Kao grupa moramo odlučiti , bloop , bloop . Zdravo , upravo smo se uključili u raspravu .
Zdravo , Joe je . Radim od kuće danas .
( Smijeh ) Zdravo , Joe . Hvala što si nam se pridružio danas .
Naš cilj danas jeste da dođemo do važnog dogovora .
Kao i meni .
&quot; Takav je moj svaki dan ! &quot;
&quot; Ovo je moj život ! &quot;
Natjeralo me na smijeh , dok nisam
zaplakao . ( Smijeh ) Jedan gospodin je napisao , &quot; &quot; Moj dnevni život do penzionisanja ili smrti &quot; &quot; .
To su stvarne rečenice koje su tužne .
Ali istina je da nismo nemoćni .
Rješenje za sindorom BPS je u našim rukama .
Bukvalno se nalazi nadomak naših prstiju .
Zove se &quot; &quot; NE BPS ! sindrom ,
( Smijeh ) što na španskom , ukoliko se sjećam svojih srednjoškolskih dana znači : &quot; &quot; Prestani ! &quot; &quot; . &quot; &quot; NE BPS &quot; &quot; sistem funcioniše na sljedeći način .
Sljedeći put kada vas pozovu na sastanak o kojem nemate mnogo infomacija , pritisnite &quot; &quot; čekanje na odgovor &quot; &quot; .
Odmah je pored &quot; &quot; prihvatam &quot; &quot; .
Ili bilo koje drugo dugme , samo ne prihvatajte odmah .
Potražite osobu koja vam je poslala pozivnicu .
Recite im da podržavate njihov rad , pitajte ih koji je povod vašeg sastanka , i recite da ste spremni da im pomognete da postignu svoj cilj .
Ukoliko to budemo radili svakodnevnije i sa dozom respekta . Možda će kolege razmisliti o tome koga će zvati i šta će biti predmet sastanaka .
Možda će vam početi slati i dnevni red sastanaka . Zamislite !
Možda neće imati konferencijske pozive sa 12 osoba , nego će takve stvari rješavati putem e-maila .
Možda će pokušati promijeniti svoje ponašanje , zbog vašeg .
I možda dobijete svoju stolicu nazad . ( Smijeh ) Recite , &quot; &quot; NE BPS &quot; &quot; sindromu .
Hvala vam .
( Aplauz )
Čak se i slijepe bebe smiješe kada čuju ljudski glas .
Danas ću govoriti o odnosu između nauke i ljudskih vrijednosti .
Općenito se podrazumijeva kako su pitanja morala , pitanja dobra i zla , ispravnog i pogrešnog , pitanja o kojima nauka službeno nema mišljenje .
Smatra se kako nam nauka može pomoći shvatiti ono što cijenimo , ali nam nikada neće moći reći šta bi trebali cijeniti .
I , prema tome , većina ljudi , i vjerovatno većina ljudi ovdje , misli kako nauka nikada neće odgovoriti na najvažnija pitanja u ljudskom životu , pitanja poput &quot; &quot; Za što vrijedi živjeti ? &quot; &quot; &quot; Za što vrijedi umrijeti ? &quot;
&quot; Šta čini dobar život ? &quot;
Zato ću objasniti kako je to iluzija , kako je odvajanje između nauke i ljudskih vrijednosti iluzija , i to prilično opasna iluzija u ovom trenutku ljudske historije .
Često se kaže kako nam nauka ne može dati temelj za moralne i ljudske vrijednosti zato što se nauka bavi činjenicama , a čini se kako činjenice i vrijednosti pripadaju različitim sferama .
Često se smatra kako ne postoji opis svijeta kakav jeste , koji nam može reći kakav bi trebao biti .
Ali ovo je očito neistina .
Vrijednosti su određena vrsta činjenica .
To su činjenice o dobrobiti svjesnih bića .
Zašto nemamo etičke obaveze prema stijenama ?
Zašto ne suosjećamo sa stijenama ?
Zato što mislimo kako stijene ne mogu patiti . A ako smo više zabrinuti za drage nam primate nego što smo za insekte , kao što i jesmo , to je zato što mislimo kako su oni izloženi većem rasponu potencijalne sreće i patnje .
Ključna stvar koju treba primjetiti ovdje je kako je to činjenična tvrdnja . To je nešto oko čega možemo biti u pravu ili u krivu . I ako krivo protumačimo odnos između biološke složenosti i mogućnosti iskustva tada bi mogli biti u krivu oko unutrašnjih života insekata .
I ne postoji mišljenje , nema verzije ljudskog morala i ljudskih vrijednosti na koje sam ikad naišao koje se u nekom trenutku ne mogu svesti na brigu o svjesnom iskustvu i njegovim mogućim promjenama .
Čak ako dobivate svoje vrijednosti iz religije , čak ako mislite kako se dobro i zlo krajnje vežu sa uvjetima života poslije smrti , bilo za vječnu sreću s Bogom ili za vječnu patnju u paklu , još uvijek ste zabrinuti o svijesti i njenim promjenama .
I reći da se te promjene mogu nastaviti poslije smrti je samo po sebi činjenična tvrdnja koja , naravno , može ili ne mora biti istinita .
Kada govorimo o uvjetima dobrobiti u ovom životu , za ljudska bića , znamo kako postoji kontinuum takvih činjenica .
Znamo kako je moguće živjeti u neuspješnom stanju , gdje sve što može poći naopako , pođe naopako , gdje majke ne mogu hraniti vlastitu djecu , gdje stranci ne mogu naći osnovu za miroljubivu saradnju , gdje se ljude ubija bez diskriminacije .
I znamo da je moguće pomicati se putem tog kontinuuma prema nečemu što je više idilično , do mjesta gdje je ovakva konferencija uopšte moguća .
I mi znamo - mi znamo - da postoje tačni i pogrešni odgovori na to kako se kretati u tom prostoru .
Da li bi bila dobra ideja dodati koleru u vodu ?
Vjerovatno ne .
Da li bi bila dobra ideja da svi vjeruju u urokljivo oko , tako da kada im se dogode loše stvari odmah krive svoje susjede ? Vjerovatno ne .
Postoje istine za spoznati o tome kako ljudske zajednice cvjetaju , neovisno o tome razumijemo li te istine ili ne .
I moral je povezan sa tim istinama .
Dakle , u razgovoru o vrijednostima govorimo o činjenicama .
Naša situacija u svijetu se može razumijeti na mnogo razina koje variraju od razine genoma sve do razine ekonomskih sistema i političkih uređenja .
Ali ako ćemo govoriti o ljudskoj dobrobiti tada , neizbježno , govorimo o ljudskom mozgu .
Zato što znamo da se naše iskustvo svijeta i nas u njemu ostvaruje u mozgu , šta god da se dogodilo nakon smrti .
Čak i ako bombaš samoubica dobije 72 djevice u zagrobnom životu , u ovom životu , njegova osobenost , njegova prilično nesretna osobenost , jeste rezultat njegovog mozga .
Dakle , doprinos kulture , ako nas kultura mijenja , kao što i čini , mijenja nas tako što mijenja naš mozak .
I stoga koja god varijacija kulture postoji u tome kako ljudska bića cvjetaju , može , barem u načelu , biti shvaćena u kontekstu nauke o umu koja se usavršava , neurologije , psihologije itd .
Dakle , ono za što se zalažem jeste da se vrijednosti svode na činjenice , činjenice o svjesnom iskustvu svjesnih bića .
Zato možemo zamisliti prostor mogućih promjena u iskustvu tih bića .
I o ovome razmišljam kao o vrsti moralnog krajolika , s vrhovima i dolinama koje odgovaraju razlikama u dobrobiti svjesnih bića , kako osobno tako i kolektivno .
Treba primjetiti kako možda postoje stanja ljudske dobrobiti koja se rijetko postižu , kojima malo ljudi ima pristup .
I ta stanja očekuju naše otkrivanje .
Možda se neka od tih stanja mogu primjereno nazvati mističnim ili produhovljenim .
Možda postoje neka druga stanja kojima ne možemo pristupiti zbog načina na koji je naš um strukturiran , ali drugi umovi bi im možda mogli pristupiti .
Sada bih želio biti jasan oko toga o čemu ne govorim . Ne govorim kako će nauka zasigurno opisati taj prostor , ili kako ćemo imati naučni odgovor na svako zamislivo moralno pitanje .
Ne mislim da ćemo , na primjer , jednog dana pitati za savjet superkompjuter kako bi saznali trebamo li imati drugo dijete , ili trebamo li bombardirati iranska nuklearna postrojenja , ili možemo li otpisati punu cijenu TED-a kao poslovni trošak .
( smijeh ) Ali ako pitanja utiču na dobrobit ljudi tada oni imaju odgovore , bez obzira da li ih možemo naći ili ne .
I samo priznanje ove činjenice , samo priznanje kako postoje dobri i loši odgovori na pitanje kako ljudi cvjetaju , promjenit će način na koji pričamo o moralu , i promjenit će naša očekivanja o ljudskoj saradnji u budućnosti .
Na primjer , u 21 državi u SAD-u zakonom je dozvoljeno tjelesno kažnjavanje u učionici . Legalno je da učitelj tuče dijete s drvenom šibom , jako , te da pritom uzrokuje velike modrice ili čak puknuće kože .
I stotine hiljada djece su podvrgnuta tome svake godine .
Položaj tih prosvjetljenih područja , vjerujem , neće vas iznenaditi .
Ne govorimo o Connecticutu .
A opravdanje za to ponašanje je izričito religiozno .
Stvoritelj svemira nam je lično rekao da je batina iz raja izašla . To stoji u Izrekama 13 i 20 , te , vjerujem , 23 .
Ali mi možemo postaviti očito pitanje : Da li je dobra ideja , uopšteno govoreći , podvrgnuti djecu boli , nasilju i javnom poniženju kao način kojim ćemo potaknuti zdravi emocionalni razvoj i dobro ponašanje ?
( smijeh ) Postoji li ikakva sumnja da to pitanje ima odgovor , i da li je taj odgovor bitan ?
Mnogi od vas bi se mogli zabrinuti kako je pojam dobrobiti zaista nedefinisan , i naizgled trajno otvoren za redefinisanje .
I stoga , kako može postojati objektivan pojam dobrobiti ?
Razmislite o analogiji , pojmu fizičkog zdravlja .
Pojam fizičkog zdravlja je nedefinisan ,
kao što nam je Michael Specter upravo rekao , mijenjao se kroz historiju .
Kada je ova statua isklesana očekivano trajanje života je vjerovatno bilo 30 godina .
Sada je oko 80 godina u razvijenom svijetu .
Možda će doći vrijeme kada ćemo promijeniti naš genom na takav način da će se nemogućnost trčanja maratona u 200. godini smatrati potpunim invaliditetom .
Ljudi će vam slati donacije kada ste u takvom stanju .
( smijeh ) Primjetite da činjenica da je pojam zdravlja otvoren , zaista otvoren za reviziju ne znači da je beznačajan .
Razlika između zdrave i mrtve osobe je jasna i značajna kao bilo koja u nauci .
Treba primjetiti da možda ima puno vrhova u moralnom krajoliku : Možda postoje jednaki načini za razvoj ; možda postoje ravnopravni načini kako organizovati ljudsko društvo , tako da se maksimizira ljudski razvoj .
Zašto ovo ne bi oslabilo objektivnu moralnost ?
Razmislite kako govorimo o hrani : Ne bih nikada usudio da vas ubjeđujem da mora postojati samo jedna ispravna hrana za jelo .
Očigledno postoji čitav niz sastojaka koji čine zdravu hranu .
Ali ipak postoji jasna razlika između hrane i otrova .
Činjenica da postoji više tačnih odgovora na pitanje &quot; &quot; Šta je hrana ? &quot; &quot; ne dovodi nas u iskušenje da kažemo kako ne postoje istine o ljudskoj ishrani .
Mnogi ljudi brinu da bi univerzalna moralnost zahtijevala moralna pravila koja ne dopuštaju izuzetke .
Tako , na primjer , ako je zaista loše lagati , mora uvijek biti loše lagati , i ako možemo naći izuzetak , onda ne postoji tako nešto poput moralne istine .
Zašto bismo tako mislili ?
Razmotrite , kao analogiju , igru šaha .
Ako ćete igrati dobar šah , princip poput &quot; &quot; Nemoj izgubiti kraljicu &quot; &quot; , jako je dobro slijediti .
Ali očigledno on dozvoljava izuzetke .
Postoje situacije kada je gubljenje kraljice odlična stvar koju možete uraditi .
Postoje trenuci kada je to jedina dobra stvar koju možete da uradite .
A ipak , šah je domen savršene objektivnosti .
Činjenica da ovdje postoje izuzeci to uopšte ne mijenja .
Znači , to nas dovodi do izvora poteza koje su ljudi skloni učiniti u moralnoj sferi .
Razmotrimo veliki problem ženskih tijela : Šta učiniti s njima ?
Ovo je jedna stvar koju možemo učiniti , možemo ih prekriti .
Stav je , opštenito govoreći , naše intelektualne zajednice da iako nam se to možda neće svidjeti , možemo smatrati kako je ovo krivo u Bostonu ili Palo Altou , ko smo mi da kažemo kako su ponosni stanovnici antičke kulture bili u krivu kada su prisiljavali svoje žene i kćeri da žive u krpenim vrećama ?
I ko smo mi da kažemo kako su oni u krivu kada ih tuku sa čeličnim kablom ili bacaju kiselinu iz baterija u njihova lica ako odbiju privilegiju da ih se uguši na ovaj način ?
Ali ko smo mi da ne kažemo to ?
Ko smo mi da se pretvaramo kako znamo toliko malo o ljudskoj dobrobiti da ne smijemo osuđivati ovakve postupke ?
Ne govorim o dobrovoljnom nošenju vela , žene bi trebale moći nositi što god žele , što se mene tiče .
Ali šta znači dobrovoljno u zajednici gdje , kada djevojka bude silovana , prvi impuls njenog oca , vrlo često da je ubije zbog srama ?
Samo dopustite toj činjenici da eksplodira u vašoj glavi na trenutak : Vaša kćerka bude silovana , a ono što želite napraviti je da je ubijete .
Koje su šanse da to predstavlja vrhunac ljudskog procvata ?
Reći ovo , ne znači reći da mi imamo savršeno rješenje u našem vlastitom društvu .
Na primjer , ovako izgleda kada odete na novinski štand skoro svugdje u civiliziranom svijetu .
Za mnoge muškarce potrebna je diploma iz filozofije da vide nešto loše u ovim slikama .
( smijeh ) Ali ako smo u raspoloženju za refleksiju možemo se zapitati : &quot; &quot; Je li ovo savršen izraz psihološke ravnoteže u odnosu na varijable kao što su mladost i ljepota ženskih tijela ? &quot; &quot; Mislim , je li ovo optimalno okruženje za odgajanje djece ?
Vjerovatno ne . Dakle , možda ima neko mjesto na spektru između te dvije krajnosti koje predstavlja mjesto bolje ravnoteže ?
( pljesak ) Možda postoji više takvih mjesta , opet , za druge promjene u ljudskoj kulturi , može biti više vrhunaca na moralnom polju .
Ali ono što treba primjetiti je kako imamo puno više načina kako ne biti na vrhuncu .
Ironija , iz moje perspektive , je kako su jedini ljudi koji se slažu sa mnom i koji misle kako postoje dobri i loši odgovori na moralna pitanja religijski demagozi ove ili one vrste .
I , naravno , oni misle da imaju prave odgovore na moralna pitanja jer su te odgovore dobili od glasa s neba , a ne zato što su napravili inteligentnu analizu uzroka i uvjeta ljudske i životinjske dobrobiti .
Zapravo , izdržljivost religije , kao leće kroz koju većina ljudi gleda moralna pitanja , odvojila je većinu govora o moralu od stvarnih pitanja ljudske i životinjske patnje .
To je razlog zašto provodimo naše vrijeme u razgovoru o stvarima kao što su homoseksualni brakovi , a ne o genocidu ili nuklearnom naoružanju ili siromaštvu ili bilo kojem drugom iznimno važnom pitanju .
Ali demagozi su u pravu oko jedne stvari , potreban nam je univerzalni koncept ljudskih vrijednosti .
Šta tome stoji na putu ?
Jedna stvar za primjetiti je da napravimo nešto drugo kada govorimo o moralu , posebno mi sekularni , akademski , naučni tipovi .
Kada govorimo o moralu vrednujemo razlike u mišljenju na način na koji to ne radimo niti u jednom drugom području našeg života .
Tako , na primjer , Dalai Lama ustaje svako jutro i meditira o suosjećanju . I on misli da je pomaganje drugom ljudskom biću sastavna komponenta ljudske sreće .
S druge strane imamo nekoga kao što je Ted Bundy . Ted Bundy je bio naklonjen otimanju i silovanju i mučenju i ubijanju mladih žena .
Dakle , čini se kako imamo istinsko neslaganje u mišljenju o tome kako korisno provoditi vrijeme .
( smijeh ) Većina intelektualaca sa Zapada gledaju na tu situaciju i kažu &quot; &quot; Pa , nema tu nečega oko čega bi Dalai Lama mogao biti zaista u pravu , zaista u pravu , ili oko čega bi Ted Bundy mogao biti u krivu što dopušta realan argument koji potencijalno upada u domen nauke .
Jedan voli čokoladu , a jedan voli vaniliju .
Ne postoji ništa što bi jedan mogao reći drugome što bi uvjerilo drugoga . &quot; &quot; I primjetite kako to ne radimo u nauci .
Na lijevoj strani je Edward Witten .
On zagovara teoriju nizova .
Ako pitate najpametnije fizičare ko je najpametniji fizičar , prema mom iskustvu pola od njih će reći Ed Witten .
Druga polovica će vam reći da im se ne sviđa pitanje .
( smijeh ) Dakle , šta bi se dogodilo kada bi se ja pojavio na konferenciji iz fizike i rekao &quot; &quot; Teorija nizova je lažna .
Ne leži mi baš . To nije ono kako ja želim vidjeti svemir u malim razmjerima .
Nisam ljubitelj . &quot; &quot; ( smijeh ) Pa , ne bi se dogodilo ništa zato što ja nisam fizičar , ja ne razumijem teoriju nizova .
Ja sam Ted Bundy teorije nizova .
( smijeh ) Ne bih htio pripadati niti jednom klubu teorije nizova koji bi me htio imati za člana .
Ali upravo to i jeste poenta .
Kada god govorimo o činjenicama određena mišljenja moraju biti isključena .
To je ono što znači imati područje stručnosti .
To je ono što znači kako znanje vrijedi .
Kako smo se uvjerili kako u moralnoj sferi ne postoji moralna stručnost , ili moralni talent ili čak moralni genije ? Kako smo se uvjerili
da se svako mišljenje mora cijeniti ? Kako smo se uvjerili
da svaka kultura ima tačku gledišta o ovim temama koje je vrijedno uzeti u obzir ?
Ima li Taliban mišljenje o fizici koje je vrijedno razmatranja ? Ne .
( smijeh ) Kako je njihova neukost išta manje očita u području ljudske dobrobiti ?
( pljesak ) Dakle , to je ono što ja mislim da je svijetu sada potrebno .
Potrebni su ljudi poput nas koji će priznati kako postoje dobri i loši odgovori na pitanja ljudskog cvjetanja , i da je moral povezan s tom domenom činjenica .
Moguće je za pojednice , ili čak za cijele kulture da brinu o krivim stvarima : Što znači kako je za njih moguće da imaju vjerovanja i težnje koje pouzdano vode do nepotrebne ljudske patnje .
Samo priznanje ovoga će preobraziti naš govor o moralnosti .
Živimo u svijetu u kojemu granice između nacija znače sve manje i manje , i jednoga dana neće značiti ništa .
Živimo u svijetu prepunom razorne tehnologije , i tu tehnologiju ne možemo učiniti neizmišljenom , uvijek će biti lakše pokidati stvari nego ih popraviti .
Zato , čini mi se jasnim da ne možemo poštivati i tolerisati beskrajne razlike u poimanju ljudske dobrobiti , ništa više nego što možemo tolerisati beskrajne razlike u poimanju kako se bolesti šire , ili u sigurnosnim standardima zgrada i aviona .
Jednostavno moramo težiti odgovorima koje dajemo na najvažnija pitanja u ljudskom životu .
A da bismo to učinili , moramo priznati da ova pitanja imaju odgovore .
Hvala vam mnogo .
( aplauz ) Kris Anderson : Ovo je zapaljiv materijal .
Bilo u ovoj publici ili među ljudima drugdje u svijetu kada čuju nešto od ovoga , ljudi bi mogli vikati od bijesa .
Čini se kako je jezik ovdje zaista bitan .
Kada govoriš o velu , govoriš o ženama koje su obučene u krpene vreće ,
Ja sam živio u muslimanskom svijetu , razgovarao sa mnogim muslimanskim ženama .
I neke od njih kažu nešto drugo . Kažu , &quot; &quot; Ovo je slavlje ženske posebnosti , pomaže da se ona sagradi i to je rezultat činjenice da ... &quot; &quot; , i to je dokazivo u sofisticiranom psihološkom pogledu , &quot; da muškoj požudi ne treba vjerovati . &quot;
Mislim , možete li ući u razgovor sa takvom ženom , a da ne izgledate kao neki kulturni imperijalist ?
Sam Harris : Da , pa mislim da sam pokušao da istaknem to u jednoj rečenici , dok sam gledao kako sat otkucava , ali pitanje je , šta je dobrovoljno u kontekstu gdje muškarci imaju određena očekivanja , i garantovano vam je da će vas tretirati na određeni način , ako ne stavite veo ?
Znači , ako neko iz ove prostorije želi da nosi veo , ili vrlo smiješan šešir , ili da tetovira lice - mislim da bi trebalo da slobodno voljno radimo šta hoćemo , ali moramo biti iskreni o ograničenjima pod kojima su ove žene .
I zato mislim da ne bi trebalo uvijek da im vjerujemo na riječ , posebno ako ima 50 stepeni napolju , a one nose burku .
C.A. : Mnogi ljudi žele vjerovati u taj koncept moralnog napretka .
Ali možeš li uskladiti to ?
Mislim kako sam te razumio kada kažeš da bi mogao to uskladiti sa svijetom koji neće postati jednodimenzionalan , gdje svi moramo misliti isto .
Reci nam , za 50 godina unaprijed , 100 godina unaprijed , kako se nadaš da će svijet izgledati , balansirajući moralni napredak sa bogatstvom .
S.H. : Mislim da , kada jednom priznamo kako smo na putu prema razumijevanju naših umova na nivou mozga , u nekim važnim pojedinostima , onda možemo priznati kako ćemo razumjeti sve naše pozitivne i negativne kvalitete u puno više detalja .
Razumjećemo pozitivne socijalne emocije kao što su empatija i saosjećanje . I razumjećemo činitelje koji ih potiču , bilo da su genetski , bilo da su način na koji ljudi razgovaraju , bilo da su ekonomski sistemi . Ukoliko to počnemo osvjetljavati , neizbježno ćemo težiti tom činjeničnom prostoru .
Neće sve biti na tanjiru .
Neće biti tako da je pokrivanje kćeri velom od rođenja jednako dobro kao što je učiti je da bude samopouzdana i dobro obrazovana u okruženju muškaraca koji imaju želju za ženama .
Hoću reći da nam ne treba Nagrada naučne fondacije da znamo kako prinudno pokrivanje velom nije dobra ideja , ali u određenom trenutku moći ćemo skenirati mozak svih koji su uključeni i stvarno ih ispitati .
Vole li ljudi jednako svoje kćeri u tim sistemima ?
I mislim da očito postoje tačni odgovori na to .
C.A. : I ako rezultat bude kako ih zaista vole jednako , jesi li spreman promjeniti svoje trenutno mišljenje o nekima od ovih stvari ?
S.H. : Pa da , po modulu jasna je činjenica kako možeš voljeti nekoga u kontekstu sistema vjerovanja koji je u zabludi .
Možete reći : &quot; &quot; Zato što sam znao kako će moj sin homoseksualac ići u pakao ako nađe momka , odrezao sam mu glavu . I to je bila najsuosjećajnija stvar koju sam mogao napraviti . &quot; &quot; Ako poslažemo sve te dijelove , mislim kako je moguće osjećati emociju ljubavi .
Ali opet , tada moramo govoriti o dobrobiti u većem kontekstu .
Svi smo mi u ovome zajedno , a ne da jedan čovjek bude u ekstazi i onda se raznese u autobusu .
C.A. : Zvuči kao razgovor koji bi ja volio nastaviti satima .
Nemamo toliko , ali možda neki drugi put . Hvala ti što si došao na TED .
S.H. : Zaista mi je čast . Hvala .
( aplauz )
