Danas ću govoriti o neočekivanim otkrićima .
Sada radim u industriji solarne tehnologije .
I moj mali početak namjerava nas gurnuti u okruženje posvećujući pažnju ...
... posvećujući pažnju zajedničkom poduhvatu .
Ovo je samo kratki video onoga što možemo uraditi .
Uh . Pričekajte trenutak .
Možda će biti potrebno par trenutaka da se učita .
( Smijeh ) Samo ćemo — možemo preskočiti — Samo ću preskočiti video umjesto ... ( Smijeh )
Ne . ( Smijeh ) ( Smijeh )
( Muzika ) To nije ... ( Smijeh )
U redu . ( Smijeh )
Solarna tehnologija je ...
O , to je bilo svo moje vrijeme ?
U redu . Hvala vam mnogo .
( Aplauz )
5 . Novembra 1990 . , čovjek po imenu El-Sajid Nosair ušetao je u jedan hotel na Menhetnu i ubio rabina Meira Kahane , lidera Židovske Lige Odbrane .
Nosair u prvi mah proglašen nevinim za ubistvo , ali dok je služio zatvorsku kaznu zbog manjih prekršaja on i drugi ljudi počeli su planirati napade na desetak poznatih znamenitosti u Njujorku uključujući tunele , sinagoge i sjedište UN-a .
Srećom , ti planovi su osujećeni od strane jednog od FBI doušnika .
Nažalost , to se nije desilo sa bombardovanjem Svjetskog trgovinskog centra 1993. godine .
Nosair je na kraju bio osuđen zbog učešća u zavjeri .
El-Sajid Nosair je moj otac .
Otac me izložio jednoj strani islama koju jako malo ljudi , uključujući većinu muslimana uspije vidjeti .
Po mom iskustvu , kada ljudi izdvoje vrijeme za interakciju jedni sa drugima ne treba puno da bi se shvatilo da uglavnom svi mi želimo iste stvari u životu .
Međutim , u svakoj religiji , u svakoj populaciji , naći ćete mali procenat ljudi koji se tako gorljivo drže svojih uvjerenja da osjećaju da moraju koristiti svako neophodno sredstvo kako bi natjerali druge da žive kao oni .
Par mjeseci prije njegovog hapšenja , posjeo me pored sebe i objasnio kako je zadnjih par vikenda , on sa nekim prijateljima išao u streljanu na Long Ajlendu kako bi vježbao gađanje .
Rekao mi je da ću ići sa njim sljedeće jutro .
Stigli smo u streljanu Kalverton , koja je bila pod prismotrom FBI a da naša grupa to nije znala .
Zadnji metak koji sam ispalio tog dana pogodio je malo narančasto svjetlo na vrhu mete i na iznenađenje svih , a posebno moje , cijela meta je prsnula u plamenovima .
Moj stric se okrenuo drugim ljudima , i rekao na arapskom &quot; &quot; ibn abduh &quot; &quot; . Kakav otac , takav sin .
Svi su se dobro nasmijali tom komentaru , ali tek nekoliko godina kasnije potpuno sam razumio šta im je bilo tako smiješno .
Mislili su da me vide u istom razaranju za koje je moj otac bio sposoban .
To su bili ljudi na koje sam gledao sa poštovanjem .
Te ljude sam zvao &quot; &quot; ammu &quot; &quot; , što znači stric .
Do moje 19. godine selio sam se već 20 puta , i ta nestabilnost u mom djetinjstvu nije mi dala neku priliku da se sprijateljim sa mnogo ljudi .
Svaki put kad se počnem osjećati ugodno u nečijoj blizini , bilo je vrijeme pakovati se i seliti se u novi grad .
Kako sam bio uvijek novo lice u razredu , često sam bio meta siledžija .
Tajio sam svoj identitet od ostalih učenika kako ne bih bio meta , ali kako se pokazalo , biti tiho , bucmasto novo dijete u razredu bilo je više nego dovoljno .
Tako sam uglavnom provodio vrijeme čitajući knjige i gledajući TV ili igrajući video igrice .
Odgajan sam da sudim ljudima na osnovu proizvoljnih parametara , kao što je rasa ili religija .
I šta mi je otvorilo oči ?
Članovi naše grupe bili su raznih zanimanja i profila .
Dan prije završetka konvencije , saznao sam da je jedno od djece sa kojima sam se sprijateljio bio Jevrej .
Trebalo je nekoliko dana da se sazna ovaj detalj , i shvatio sam da nije bilo prirodnog neprijateljstva između nas .
Druga velika prekretnica je bila kada sam našao ljetni posao u Buš Vrtovima , zabavnom parku .
Tu sam bio izložen ljudima svih religija i kultura , i to iskustvo se pokazalo fundamentalno za razvoj mog karaktera .
Cijelog života su me učili da je homoseksualnost grijeh , i u skladu s tim , svi homoseksualci su predstavljali negativan uticaj .
Zbog tog osjećaja , mogao sam suprotstaviti stereotipe kojima su me učili kao dijete sa stvarnim životnim iskustvom i interakcijom .
Zatim , tu je bio &quot; &quot; Dnevni šou &quot; &quot; . Svake noći , Džon Stjuart me natjerao da budem intelektualno iskren prema sebi apropo svoje netrpeljivosti i pomogao mi je da shvatim da nečija rasa , religija ili seksualna orjentacija nema ništa sa kvalitetom njihova karaktera .
Na mnoge načine , on je za mene bio očinska figura onda kad mi je očajno trebala .
Inspiracija može često doći iz neočekivanog mjesta , i činjenica da je jedan Jevrej komičar uradio više da pozitivno utiče na moj pogled na život od mog oca ekstremiste nije mi promakla .
U tom momentu , shvatio sam koliko negativne energije treba da držite toliku mržnju u sebi .
Zak Ebrahim nije moje pravo ime .
Promijenio sam ga kad je moja porodica odlučila da okonča vezu sa mojim ocem i počne novi život .
Zašto onda da se izlažem i potencijalno stavljam u opasnost ?
Jednostavno je .
Radim to u nadi da će možda neko jednog dana ko se osjeća prisiljenim da koristi nasilje čuti moju priču i shvatiti da postoji bolji put , da iako sam bio podvrgnut toj nasilnoj , netolerantnoj ideologiji , nisam postao fanatičan .
Umjesto toga izabrao sam svoje iskustvo da se borim protiv terorizma , protiv netrpeljivosti .
Radim to za žrtve terorizma i njihove najbliže , za užasan bol i gubitak koje im je terorizam uzrokovao .
Govorit ću glasno , za žrtve terorizma protiv svih bemislenih djela i osuditi djela moga oca .
I sa tom činjenicom , stojim ovdje kao dokaz da nasilje nije ukorijenjeno ni u jednoj religiji ili rasi , i da sin ne mora slijediti svoga oca .
Ja nisam moj otac .
Hvala vam . Hvala vam , svima . Hvala vam svima . Hvala puno .
Podjeliću sa vama priču o tome kako sam postala HIV / AIDS aktivist .
Ime moje kampanje je SING kampanja .
U novembru 2003 pozvana sam da učestvujem u pokretanju Mandelove 46664 Fondacije . To je njegova HIV / AIDS fondacija .
A 46664 je broj koji je Mandela nosio dok je bio zarobljen na ostrvu Roben .
To sam ja sa Jusu N &apos; Dur na bini , najbolji trenutak u mom životu .
Sledećeg dana , svi umjetnici su pozvani da se pridruže Mandeli na Roben ostrvu , gdje je trebao da održi konferenciju svjetskim novinarima , ispred svoje nekadašnje zatvorske ćelije .
Možete da vidite rešetke na prozoru .
Bila je to sasvim važna prilika za sve nas .
U tom trenutku , Mandela je izjavio za svjetsko novinarstvo da je to bio virtualni genocid koji se dešavao u njegovoj zemlji , ta post-segregacijska nacija , gdje je hiljade ljudi umiralo svaki dan , a žrtve sa prve linije , koje su bile najviše ranjive , su bile žene i djeca .
To je bio ogroman uticaj na moju svijest , zbog toga što sam ja žena i majka , a nisam znala da je HIV / AIDS pandemija toliko direktno pogađala žene .
Onda sam se obavezala — kada sam napustila Južnu Afriku , napuštajući Kejptaun , rekla sam sebi , &quot; &quot; Ovo će biti nešto o čemu moram govoriti .
Moram služiti drugima . &quot; &quot; I od tada učestovala sam u svakom događaju 46664 fondacije u kojem sam mogla učestovati održavala sam konferencije za novinare , davala intervjue , govoreći i koristeći svoju platformu muzičara , sa posvećenošću Mandeli , iz poštovanja za ogroman , nevjerovatan rad koji je on postigao .
Svi ljudi na svijetu poštuju Nelsona Mandelu . Svi obožavaju Nelsona Mandelu .
Ali da li oni svi znaju šta se dešavalo u Južnoj Africi , u njegovoj zemlji , zemlji poznatoj po najvećem broju incidenata prenosa virusa ?
Ja mislim da ako sada izađem na ulicu , i kažem ljudima šta se tamo dešavalo , oni bi bili šokirani .
Ja sam bila veoma sretna , nekoliko godina poslije , što sam upoznala Zakija Ahmata , osnivača kampanje Akcija Liječenja , nevjerovatnog borca i aktivistu .
Upoznala sam ga na skupu 46664 .
Nosio je majicu istu kao što ja nosim sada .
To je sredstvo . To vam govori ja se solidarišem sa ljudima koji su HIV pozitivni , sa ljudima koji žive sa HIV-om .
I na neki način , zbog predrasude , noseći ovu majicu , ja kažem , &quot; &quot; Jeste , mi možemo pričati o ovom problemu .
To ne mora biti sakriveno . &quot; &quot; Postala sam član kampanje Akcija Liječenja , i veoma sam ponosna što sam član te nevjerovatne organizacije .
To je fundamentalna kampanja koju čine uglavnom žene , njih 80 posto , većina njih je HIV - pozitivna .
One rade na tom polju .
Imaju ogroman doseg ljudi koji su direktno pogođeni virusom .
Oni imaju programe obrazovanja .
Oni iznose probleme predrasude .
Izvanredno je to što čine .
Da , moja SING kampanja je poduprijela Kampanju Akcija Liječenja na način gdje sam ja pokušala da podignem svijest i takođe pokušala da sakupim novac .
Dosta novca koje sam uspjela sakupiti je direktno otišlo u Kampanju Akcija Liječenja i u nevjerovatan posao koji oni obavljaju , i koji još uvijek čine , u Južnoj Africi .
Ovako izgleda moja SING Kampanja .
SING Kampanju uglavnom činim ja i oko troje ili četvero izvanrednih ljudi koji me podržavaju .
Proputovala sam čitav svijet u protekle dvije i pol godine . Posjetila sam oko 12 različitih zemalja .
Ovo sam ja u Oslu u Norveškoj , primajući lijep , debeo ček , ovdje pjevam u Hong Kongu , pokušavajući sakupiti novac .
U Johanesburgu , imala sam priliku da sviram za publiku uglavnom bjele , srednje klase u Južnoj Africi koja je završila u suzama , iz razloga što ja koristim filmske snimke koje su doprle do srca , čitavu narav , ove užasne tragedije koja se dešava , koju ljudi namjeravaju izbjeći , zato što su iscrpljeni , i oni sasvim ne znaju šta bi moglo biti riješenje .
Aron Motsoaledi , sadašnji ministar zdravlja , prisustovao je ovom koncertu , i ja sam imala priliku da ga upoznam , i on se absolutno obavezao da će pokušati napraviti promjenu , koja je absolutno potrebna .
Ovo je Škotski parlament .
gdje sam ja postala izaslanik za Škotsku i HIV .
Pokazivala sam im svoja iskustva i pokušala , ponovo , da podignem svijest .
Još jedanput , u Edinburgu , sa predivnim Afričkim Dječijim Horom kojeg ja jednostavno obožavam .
A to su djeca kao ova , mnogi od njih su siročad zbog toga što su njihove porodice zaražene virusom side .
Ovdje sjedim sa Mišel Sidibe u Njujorku . On je direktor UNAIDS-a .
I veoma sam počašćena činjenicom da me je Mišel pozvao , samo par mjeseci prije , nego što je postao UNAIDS ambasador .
Na taj način , ja sam osnaživala svoju platformu i širila svoj doseg .
Poruka koju UNAIDS trenutno šalje svijetu jeste da želimo da vidimo virtualnu eliminaciju prenosa virusa od majke na dijete do 2015 godine .
To je veoma ambiciozan cilj , ali mi vjerujemo da može biti postignut političkom voljom .
To je moguće .
A ovdje sam ja sa trudnicom koja je HIV pozitivna , mi smo nasmijane , obadvije smo nasmijane , jer smo vrlo pouzdane pošto znamo da ta mlada žena prima liječenje tako da njen život može biti produžen da bi se mogla brinuti o bebi koju treba da rodi .
A njena beba će primit PMTCT , što će značiti da ta beba može biti rođena bez virusa .
To je prevencija na samom početku života .
To je jedan način gledanja na intervenciju pandemije side .
Sada bih voljela da završim tako što ću vam ispričati priču o Avelili .
Ovo je Avelili . Ona ide sa mnom gdje god da pođem .
Ja pričam o njoj svima , jer ona predstavlja jedno od milion siročadi zaraženo virusom side .
Avelilina majka je imala HIV virus . Ona je umrla od bolesti side .
Avelili je imala virus . Ona je bila rođena sa virusom .
Ovdje je ona sa sedam godina , težine ne više od jednogodišnje bebe .
U ovome trenutku svog života , ona pati od bolesti side u punom procvatu a imala je i upalu pluća .
Upoznali smo je u bolnici u Istočnom Kejpu i proveli čitavo poslijepodne sa njom — predivno dijete .
Doktori i sestre su bili fenomenalni .
Odredili su joj vrlo posebnu ishranu i dobro se brinuli o njoj .
Nismo znali kada smo napustili bolnicu — pošto smo snimili njenu priču — da li će ona uopšte preživjeti .
To je bio očigledno ... jedan vrlo emocionalan susret koji nas je ostavio da se osjećamo vrlo rezonantno sa ovim direktnim iskustvom , ovim jednim dijetetom , znate , sa tom pričom .
Pet mjeseci kasnije , vratili smo se u Južnu Afriku da vidimo ponovo Avelili .
Počinjem — da se ježim — ne znam da li možete da vidite dlake na mojim rukama .
One su uspravne , zato što znam šta ćcu vam sada pokazati .
Ovo je transformacija koja se desila .
Nije li to izvanredno ?
( Aplauz ) Taj aplauz je ustvari za doktore i sestre bolnice koja se brinula o Avelili .
Ja smatram da vi cijenite tu vrstu transformacije .
Stoga bih vam poručila , svima u publici , ako osjećate da svaka majka i svako dijete u svijetu ima pravo na pristup dobroj ishrani i dobroj zdravstvenoj njezi , i ako vjerujete da Ciljevi Mileniumskog Razvoja , naročito peti i šesti , kojima se trebaju posvetiti sve vlade širom svijeta — naročito u Saharskoj Africi — molim vas da ustanete .
Ja mislim da je to korektno za reći , to su skoro svi u dvorani .
Hvala vam najljepša .
( Aplauz )
Kupicu to . Imam puno novaca .
Imam toliko novaca da ce mi trebati vjecnost .
Ovo su jednostavni predmeti : satovi , ključevi , češljevi , naočale .
To su stvari koje su žrtve genocida u Bosni nosile sa sobom na njihovom posljednjem putovanju .
Svima su nam poznati ovi uobičajeni , svakodnevni predmeti .
Uglavnom , govoreno im je da će biti razmjenjeni za zarobljenike rata .
Ovi predmeti su pronađeni u brojnim masovnim grobnicama širom moje domovine , i dok sada pričamo , forenzičari ekshumiraju tijela iz novootkrivene masovne grobnice , 20 godina poslije rata .
I vjerovatno je najveća ikada otkrivena .
Tokom četiri godine sukoba koji je razorio bosansku naciju u ranim 90-im , oko 30.000 građana , uglavnom civila je nestalo , vjerovatno ubijeno , i još 100.000 je ubijeno tokom ratnih operacija .
Većina njih je ubijena ili u prvim danima rata ili pri kraju sukoba , kada su sigurne zone UN-a , poput Srebrenice , pale u ruke srpske vojske .
Međunarodni tribunal je izrekao nekoliko presuda za zločine protiv čovječnosti i genocida .
Genocid je sistematsko i namjerno uništavanje rasnih , političkih , vjerskih ili etničkih grupa .
Koliko god je genocid vezan za ubijanje ,
toliko ima veze i sa uništavanjem njihove imovine , njihovog kulturološkog nasljeđa , i u konačnici bilo kakvog traga o tome da su oni ikada i postojali .
Genocid nije samo ubijanje ; to je i osporavanje identiteta .
Uvijek postoje tragovi - ne postoji savršen zločin .
Uvijek postoje ostaci poginulih koji su dugotrajnijih od njihovih krhkih tijela i našeg selektivnog i slabog sjećanja na njih .
Niti jedno tijelo ne bi trebalo ostati neotkriveno ili neidentificirano .
Ovi predmeti se koriste kao forenzički dokazi prilikom vizuelne idektifikacije žrtava ali također služe i kao veoma vrijedni forenzički dokazi u sadašnjim suđenjima za ratne zločine .
Preživjeli bivaju povremeno pozvani da pokušaju identifikovati ove predmete fizički , ali fizičko prepoznavanje je veoma zahtjevno , neefikasno i veoma je bolan proces .
Mnogi od njih bivaju uništeni , vjerovali ili ne , ili jednostavno uskladišteni , daleko od očiju i od uma .
Prije nekoliko godina sam odlučio da fotografišem svaki ekshumirani predmet kako bih napravio vizuelnu arhivu koju preživjeli mogu sa lahkoćom pretraživati .
Budući da sam pripovjedač , volim raditi za zajednicu ,
volim ići iza podizanja svijesti .
I u ovom slučaju , neko bi mogao prepoznati ove predmete ili će barem njihove fotografije ostati kao trajni , nepristrasni i precizni podsjetnik o tome šta se desilo .
Fotografija je vezana za empatiju , i to koliko su ovi predmeti poznati garantuje empatiju .
U ovom slučaju , ja sam samo sredstvo , forenzičar , ako želite , i rezultat je fotografija koja je najbliža tome da bude dokument .
Uz svu njihovu jednostavnost , ovi predmeti su posljednji svjedok identiteta žrtava , posljednji vječni podsjetnik da su ovi ljudi ikada postojali .
Hvala vam .
Bila sam dobar učenik u školi . Očekivalo se mnogo od mene , i sa slavljem sam počela svoj studentski život sa magistarskim studijama , zabavama , životom pod punim gasom .
Napustila sam seminar kada je počeo , prepuštena pretrazi po svojoj torbi , kao što sam i ranije ponekad radila , kad sam odjednom čula glas koji šapuće : &quot; Napušta salu . &quot;
&quot; Ona otvara vrata . &quot;
To je bio početak . Glas se vratio .
I glas je nastavio danima i nedeljama , sve više i više pričajući sve šta sam radila u trećem licu .
&quot; ide na čas . &quot;
Bio je neutralan , nezaustavljiv , čak na trenutke , čudno prijateljski i uvjerujući , iako sam primijetila da je taj smirujući ton ponekad bio usitnjen , i da je reflektirao moja osobne neiskazane osjećaje .
Suptilan proces uslovljavanja je počeo , činjenica da obični ljudi ne čuju glas , dok ga ja čujem , pokazuje da nešto ne valja .
Provodila sam neko vreme objašnjavajući doktoru opšte prakse na fakultetu
U tom stadijumu su događaji počeli se brzo odvijati .
Ali , dok sam bila ohrabrivana da gledam na glas ne kao iskustvo , već kao simptom moj strah i otpornost na njega su se pojačavali .
Najbitnije , sve to se ispoljilo agresivno pozicijom nasuprot moje duše kao neke vrst fizičkog civilnog rata , i na svoj način , to je prouzrokovalo brojne glasove , koji su progresivno postajali neprijateljski i prijeteći .
Vidiš li tu čašu vode ?
Dvije godine kasnije , degradacija je dosegla svoj zenit .
Dostigla sam sam vrh repertoara : zastrašujući glasovi , groteskne vizije , čudni i nezaustavljivi ushićaji .
Danas , kada razmišljam o tom brodolomu i beznađu tih godina , čini mi se kao da je neko umro u tom prostoru i zbog toga , i neko drugi je bio spašen .
Slomljena i ukleta osoba je preuzela to putovanje , a osoba koja je napusitla bila je spasilac , i završila kao osoba koja mi je suđena da postanem .
Dosta ljudi mi je činila zlo tokom života i sjećam se svih njih ali ta sjećanja blijede i iščezavaju u poređenju sa ljudima koji su mi pomogli .
Uvjeren sam da će Eleanor prevazići ovo .
Na početku sam i vjerovala .
U stilu : &quot; &quot; Čuvajte se .
Imam plastičnu vilicu ! &quot; &quot; Strateški .
Treba napomjenuti da sam završila sa skupljanjem svojih dijelova , svaki fragment je predstavljen različitim glasom koji sam odvajala pomalo od svojih lijekova , i vratila sam se psihijatru , ali ovaj put sa druge strane granice .
Danas sam veoma ponosna da učestvujem u &quot; &quot; Intervoice &quot; &quot; -u , internacionalnoj organizaciji pokreta &quot; &quot; Hearing Voices &quot; &quot; inicijative inspirisane poslovima profesora Marius Rommea i doktora Sandre Escher , koji pojavljivanje glasova tretira kao stategiju preživljavanja , kao zdravu reakciju na lude pojave , ne kao čudan simtom šizofrenije koji se mora liječiti , već kao kompleksno iskustvo , važno i posebno , koje se mora istražiti .
Taj tip društva nije samo moguć , već se uveliko stvara .
Parafraziraću Chavez-a , jednom kada društvena promjena počne , ne može se preokrenuti .
Ne možemo poniziti osoba koja se osjeća ponosno .
Ne možemo suzbiti ljude koji nemaju straha .
Tokom posljednjih 20 godina , pokret &quot; &quot; Hearing Voices &quot; &quot; stvorio je mrežu slušalaca u 26 zemalja , na 5 kontinenata , radeći zajedno kako bi promovisali dostojanstvo , solidarnost i autonomizaciju osoba sa mentalnim poremećajem , i kako bi stvorili novi jezik i novu praksu nade , u centru u kome se nalazi stabilna vera , u snazi individue .
Kao što je Peter Levine rekao , ljudska životinja je jedinstveno biće sa instiktivnim kapacitetom da se bori , i sa neophodnom intelektualnom snagom za iskazivanje tog unutarnjeg kapaciteta .
U tom smislu , za članove jednog društva , ne postoji veća čast ili privliegija , od olakšanja nečijeg procesa ozdravljenja , da mu se ispovedi , da ga podrži , podijeli bol od koje osoba pati , i pruži mu nadu za ozdravljenje .
Jedinstveni smo . Nezamenljivi .
Svjetlo je uvijek na kraju tunela .
Pričajte mi o sebi . &quot; &quot; Hvala vam .
( Pljesak )
Kris Anderson : Julian , dobrodošao .
Došli smo do saznanja da je VikiLiks , vaše djelo , u zadnjih nekoliko godina objavio više povjerljivih dokumenata nego ostatak svijetskih medija zajedno .
Da li je to zaista moguće ?
Julian Asanž : Da , da li je to zaista moguće ?
To je zabrinjavajuće — zar ne ? — da ostatak svjetskih medija radi tako loš posao da mala grupa aktivista je u mogućnosti da objavi više te vrste informacija nego ostatak svijetske štampe zajedno .
KA : Kako to funkcioniše ?
Kako ljudi objavljuju te dokumente ?
I na koji način čuvate njihovu privatnost ?
JA : Postoje — onoliko koliko mi možemo reći — klasični zviždači . A mi posjedujemo više načina dostupnim njima za dostavljanje informacija .
Tako što koristimo najusavršenije šifrovanje da prebacimo stvari preko interneta , da sakrijemo tragove , provučemo ih kroz pravne nadležnosti kao Švedska i Belgija da sprovedemo te pravne zaštite .
Mi te informacije dobivamo poštom , običnom poštom , šifrovane ili ne , pregledamo ih kao obična novinarska kuća , presložimo — što je ponekad to nešto što je teško za uraditi , kada govorite o ogromnim bazama informacija — objavimo to u javnosti i onda se branimo od neizbježnih pravnih i političkih napada .
KA : Znači vi se trudite da osigurate da su dokumenti legitimni . Ali vi ustvari skoro nikad ne znate pravi identitet izvora informacija .
JA : To je tačno , da . Vrlo rijetko mi ikad saznamo . I onda kada saznamo u tom trenutku mi uništimo tu informaciju što je prije moguće .
( Telefon zvoni ) Do vraga .
( Smijeh ) KA : Ja mislim da to CIA želi znati koja je šifra za TED članstvo . ( Smijeh )
Hajmo uzeti za primjer , ustvari .
To je nešto što ste objavili prije nekoliko godina .
Ako možete prikazati ovaj dokumenat ...
Znači ovo je bila priča u Keniji prije nekoliko godina .
Možete li reći šta ste to objavili i šta se desilo ?
JA : To je ustvari Krolski izvještaj .
To je bio izvještaj tajne obavještajne službe naručen od strane Kenijske vlade nakon izbora 2004 .
Prije 2004 , Kenijom je upravljao Danijel arap Moi oko 18 godina .
On je bio blagi diktator u Keniji .
I onda kada je Kibaki došao na vlast — kroz koaliciju snaga koje su pokušavale da počiste korupciju u Keniji — naručili su ovaj izvještaj , potrošili su oko dva miliona funti na ovaj i još jedan izvještaj .
A onda je vlada to skrivala i iskoristila to kao političku prednost nad Moiem , koji je bio najbogatiji čovjek — i još uvijek je najbogatiji čovjek — u Keniji .
To je Sveti Gral Kenijskog novinarstva .
Otišao sam tamo 2007 godine , i uspjeli smo doći do ovoga pred same izbore — nacionalne izbore , 28 . Decembra .
Kada smo objavili taj izvještaj , učinili smo to tri dana nakon što je novi predsjednik , Kibaki , odlučio da se udruži sa čovjekom kojeg je želio da se riješi , Danijelom arap Moiem . Tako je ovaj izvještaj postao kamen oko predsjednikovog vrata .
KA : I — da skratimo ovu priču — došlo je do saznanja o izvještaju u Keniji , ne od službenih medija , već neposredno . I po vašem mišljenju , to je promjenilo izbore .
JA : Da . To je postala naslovna strana Gardijana i tada je odštampano u svim susjednim zemljama Kenije , u Tanzanijskoj i Južno Afričkoj štampi .
A došlo je izvana .
I to je , nakon nekoliko dana , učinilo da se Kenijsko novinarstvo osjeća slobodno da priča o tome .
A prikazivalo se ravno 20 noći na Kenijskoj Televiziji , što je promjenilo izbore za 10 procenata , prema izvještaju Kenijske obavještajne službe , što je potpuno promjenilo rezultate izbora .
KA : Opa , znači vaše objavljivanje je zaista uveliko promjenilo svijet ?
JA : Da .
( Aplauz ) KA : Ovdje — Mi ćemo da pokazemo kratki isječak iz ovog snimka vazdušnog napada u Bagdadu .
Čitav snimak je duži. ali ovo je kratki isječak .
Ovo je — osjetljiv materijal , da vas upozorim .
Radio : ... samo jebeno , kad ih naciljaš otvori vatru .
Vidim vaš element , uh imam oko četiri Humvija , uh tamo pored ...
Čisto je . U redu . Pucam .
Javite mi kad ih pogodite . Pucajmo .
Zapalite ih sviju .
Hajde , otvori vatru !
( pucnjava iz oružja ) Nastavite da pucate . Nastavite da pucate . ( pucnjava iz oružja ) Nastavite da pucate .
Hotel ... Bušmaster 2-6 , Bušmaster 2-6 ,
moramo da se pokrenemo , sada !
Uredu je , sada smo naciljali svih osam osoba .
Da , vidimo dvije ptice ( helikopteri ) , i još uvijek pucamo .
Prijem . Imam ih .
2 - 6 , ovo je 2 - 6 , mi smo u pokretu .
Ups , izvinjavam se . Šta se dešavalo tamo ?
Do vraga , Kajl . U redu , hahaha . Pogodio sam ih .
KA : Onda , kakav je bio uticaj toga ?
JA : Uticaj na ljude koji su radili na tome bio je ogroman .
Mi smo onda poslali dvoje ljudi u Bagdad da detaljnije istraže tu priču .
To je samo prvi od tri napada koji se desio u toj sceni .
KA : Znači li to da je 11 ljudi poginulo u tom napadu , uključujući dva Rojtersova radnika ?
JA : Da . Dva Rojtersova radnika , i dva mala dijeteta su bila ranjena .
Tamo je ukupno poginulo izmedju 18 i 26 ljudi .
KA : I objavljivanje ovoga je prouzrokovalo ogroman bijes posvuda .
Koji je bio ključni faktor svega ovoga što je ustvari prouzrokovalo sav taj bijes , šta vi mislite ?
JA : Neznam , pretpostavljam da ljudi mogu vidjeti ogromno neslaganje u sili .
Imate ljude koji opušteno hodaju ulicom , a onda Apač helikopter udaljen jedan kilometar ispaljuje 30-milimetarske rakete po svima — tražeći bilo kakav izgovor za to — i ubija ljude koji spašavaju ranjene .
I tu su bila upletena dva novinara koji očigledno nisu bili pobunjenici jer to je njihov svakodnevni posao .
KA : Postoji , jedan analitičar Američke obavještajne službe , Bradli Maning , koji je uhapšen . I on je navodno priznao u &quot; &quot; chat &quot; &quot; sobi da vam je dostavio ovaj snimak , zajedno sa 280 000 povjerljivih telegrama Američke ambasade .
Mislim , da li je ?
JA : Pa zapravo , mi smo porekli primanje tih telegrama .
On je optužen , prije nekih pet dana , za posjedovanje 150 000 telegrama i objavljivanje 50 .
Mi smo objavili početkom ove godine telegram iz Američke ambasade u Reykjaviku . Ali to ne mora biti povezano .
Ja sam bio poznat posjetilac te ambasade .
KA : Mislim , ako ste primili na hiljade diplomatskih telegrama Američke ambasade ...
JA : Mi bismo ih objavili . ( KA : Biste ? ) JA : Da . ( KA : Zašto ? ) JA : Zbog toga što takve stvari otkriju pravu istinu recimo , o Arapskim vladama , istinske povrede ljudskih prava u tim vladama .
Ako pogledate telegrame koji su otkriveni , to je taj materijal koji se tamo nalazi .
KA : Hajde da pričamo malo opširnije o tome .
Uopšteno , kakva je vaša filozofija ?
Zašto je u redu ohrabrivanje objave tajnih informacija ?
JA : Pa , postoji pitanje koja vrsta informacija je važna u svijetu , i koja vrsta informacija može donijeti promjenu .
A postoji mnogo informacija .
Znači informacije za koje organizacije troše ekonomske napore da ih sakriju , su vrlo dobar znak da kada te informacije procure , postoji nada da se napravi nešto dobro . Jer organizacije koje ih poznaju najbolje , a poznaju ih izvana i iznutra , troše trud da ih sakriju .
A to je ono što smo vidjeli u praksi . I to je historija novinarstva .
KA : Dali postoje rizici s time , bilo za pojedince koji su umiješani u to ili za društvo u cijelini , gdje objavljivanje zapravo može imati nenamjerne posljedice ?
JA : Mi to nismo primjetili u vezi sa bilo čim što smo objavili .
Pošto mi imamo politiku imunizacije štete .
Imamo način na koji radimo sa informacijama koje posjeduju neku vrstu ličnih identifikacionih informacija u sebi .
Ali postoje legitimne tajne — znate , vaš zdravstveni karton : to je legitimna tajna . Ali mi se susrećemo sa zviždačima koji nam dolaze a koji su vrlo dobro motivisani .
KA : Znači oni jesu dobro motivisani .
A šta biste rekli , na primjer , roditelju nekoga — čiji sin služi Američku vojsku , i on vam kaže , &quot; &quot; Znate šta , objavili ste nešto za šta je neko imao inicijativu da to objavi .
To pokazuje američkog vojnika kako se smije ljudima koji umiru .
To daje utisak — upravo je dalo utisak milionima ljudi u svijetu da su američki vojnici nehumani .
Ustvari , oni to nisu . Moj sin nije . Kako se usudjujete ? &quot; &quot; Šta biste vi rekli na to ?
JA : Da , imamo dosta i toga .
Ali znajte , ljudi u Bagdadu , ljudi u Iraku , ljudi u Afganistanu — oni ne trebaju da vide taj snimak : oni to vide svaki dan .
Znači to neće promjeniti njihovo mišljenje . To neće promjeniti njihovu percepciju .
To je ono što oni vide svaki dan .
To će promjeniti percepciju i mišljenje ljudi koji za sve to plaćaju . I tome se mi nadamo .
KA : Znači pronašli ste način da osvijetlite ono što vidite kao vrstu mračnih tajni u kompanijama i vladama .
Svijetlo je dobro .
Ali da li vi vidite ironiju u činjenici da , da biste osvijetlili s tim svijetlom , sami morate stvoriti tajnovitost vaših izvora ?
JA : Ne sasvim . Mi nemamo još uvijek bilo kakve &quot; &quot; dizidente &quot; &quot; VikiLiksa .
Mi nemamo izvore koji se ne slažu s drugim izvorima .
Ako bi oni istupili , bila bi to nezgodna situacija za nas . Ali mi po svoj prilici radimo na takav način da se ljudi osjećaju moralno primoranim da nastave našu misiju , a ne da je zafrknu .
KA : Interesuje me , na osnovu svega što smo čuli do sada — zanima me mišljenje TED publike .
Pošto znate , možda postoji par mišljenja o VikiLiks-u i o Julijanu .
Znate već , heroj — narodni heroj — unosi ovo vazno svijetlo .
Opasni smutljivac .
Ko misli da je heroj ?
Ko misli da je opasni smutljivac ?
JA : Ma hajde . Mora biti neko .
KA : To je blaga publika , Julijane , blaga publika .
Moramo pokušati bolje . Hajde da im pokažemo drugi primjer .
Ovdje je nešto što još niste objavili , ali objavljujete za TED .
Mislim to je intrigantna priča koja se upravo desila , tačno ?
O čemu se radi ?
JA : Ovo je primjer onoga što mi radimo skoro svaki dan .
Znači pred kraj prošle godine — u novembru prošle godine — desilo se niz eksplozija na bušotinama u Albaniji kao ona u Meksičkom zaljevu , ali ne tako velike .
I dobili smo izvještaj — vrstu inženjerske analize o tome šta se desilo — koji govori da su pripadnici obezbjedjenja nekih suparničkih naftnih kompanija ustvari parkirali kamione tamo i onda ih digli u zrak .
I dio albanske vlade je bio umješan , itd . , itd .
A inženjerski izvještaj nema nikakvo uzglavlje . Tako da je to bio jako težak dokument za nas .
Nismo mogli da ga verifikujemo jer nismo znali ko ga je napisao a znali smo o čemu je .
Tako da smo bili skeptični misleći da se to neka suparnička naftna kompanija poigrava sa tim problemom .
Pod tim okolnostima , objavili smo to i rekli , &quot; &quot; Gledajte , mi smo skeptični u vezi ovoga .
Ne znamo , ali šta možemo ?
Materijal izgleda dobro , osjećaj je dobar , ali mi jednostavno ne možemo to provjeriti . &quot; &quot; A onda smo primili pismo baš ove sedmice od kompanije koja ga je napisala , želeći da otkrije izvor — ( Smijeh ) u kojem piše , &quot; &quot; Hej , mi želimo da otkrijemo izvor . &quot; &quot; A mi smo rekli , &quot; &quot; O recite nam nešto više .
O kakvom dokumentu vi govorite tačno ?
Možete li dokazati da vi posjedujete taj dokumenat ?
Da li je on stvarno vaš ? &quot; &quot; Oni su nam onda poslali ovaj snimak ekrana sa autorom u formatu &quot; &quot; Microsoft Word-a &quot; &quot;
Da .
( Aplauz ) To se dešavalo mnogo puta .
To je jedna od naših metoda identifikovanja — provjeravanja materijala , to što pokušavamo da nagovorimo te ljude da pišu pisma .
KA : Da . Da li ste imali informacije unutar BP-a ?
JA : Da , imamo mnogo , ali mislim , u ovom trenutku , ulažemo velik trud u sakupljanju novčanih sredstava i u izgradnju .
Tako da je stepen našeg objavljivanja u zadnjih nekoliko mjeseci sveden na minimum dok mi preuredjujemo naše pozadinske sisteme za izvanredno zanimanje javnosti koje mi imamo .
To je problem .
Kao svaka početna organizacija koja raste , mi smo oduševljeni našim rastom . A to znači da dobivamo ogomnu količinu informacija od strane zviždača vrlo visokog kalibra , ali nemamo dovoljno ljudi da ustvari procesiramo i pregledamo te informacije .
KA : Znači to je glavni problem , uglavnom novinari volonteri i / ili finansiranje novinarskih plaća ?
JA : Da . Tako je , i ljudi kojima vjerujemo .
Pa mislim , mi smo organizacija kojoj je teško rasti vrlo brzo zbog vrste materijala sa kojim radimo . Moramo se restruktuirati da bi smo imali ljude koji će raditi sa stvarima najviše državne bezbjednosti , a onda sa slučajevima niže bezbjednosti .
KA : Pomozite nam da vas bolje upoznamo i kako ste otpočeli ovaj posao .
Mislim da sam pročitao da ste kao dijete išli u 37 različitih škola .
Da li je to tačno ?
JA : Pa dobro , moji roditelji su bili u filmskoj industriji a onda u bijegu od kulta , tako da kombinacija izmedju to dvoje ...
( Smijeh ) KA : Mislim , psiholog bi mogao reći da je to recpat za razvijanje paranoje .
JA : Šta , filmska industrija ?
( Smijeh ) ( Aplauz ) KA : Također ste bili — mislim , bili ste haker u mlađoj životnoj dobi i susreli ste se s vlastima prilično rano .
JA : Pa dobro , bio sam novinar .
Znate , bio sam vrlo mlad novinar aktivist u ranoj životnoj dobi .
Pisao sam časopis , bio osudjivan zbog toga kao tinejdžer .
Tako da morate biti oprezni sa hakiranjem .
Mislim postoji kao — postoji metod koji se može upotrijebiti za različite stvari .
Nažalost trenutno , najviše je upotrebljavan od strane ruske mafije da bi se kralo sa računa vaših baka
Tako da ta fraza nije — tako lijepa kao što je prije bila .
KA : Da , ja zasigurno ne mislim da vi kradete sa računa bilo čije bake . Ali šta je sa vašim osnovnim vrijednostima ?
Možete li nam objasniti koje su to i možda navesti poneki incident iz vašeg života koji je pomogao da ih odredi ?
JA : Nisam siguran u vezi incidenta .
Ali osnovne vrijednosti : pa , sposobni , velikodušni ljudi ne stvaraju žrtve : oni njeguju žrtve .
A to je nešto što je poteklo od mog oca i nešto od drugih sposobnih , velikodušnih ljudi koji su bili u mome životu .
KA : Sposobni , velikodušni ljudi ne stvaraju žrtve : oni njeguju žrtve ?
JA : Da . I znate , ja sam ratoborna osoba , tako da nisam pretjerano dobar u njegovanju . Ali na neki način — Postoji drugi način njegovanja žrtava , a to je hvatanje počinioca krivičnih djela .
A to je nešto što je dio mog karaktera veoma dugo .
KA : Recite nam , na brzinu , u posljednoj minuti , priču : šta se desilo na Islandu ?
Ustvari ste objavili nešto tamo , susreli se sa problemom s bankom , a onda je novinarskoj agenciji tamo zabranjeno da objave tu priču .
Umjesto toga , oni su objavili vašu stranu priče .
To vas je učinilo važnom osobom na Islandu . Šta se zatim desilo ?
JA : Da , to je velik slučaj , znate .
Island je prošao kroz finansijsku krizu .
Bio je to najjači udarac na neku zemlju u svijetu .
Njihov bankarski sektor je bio 10 puta BDP-a veći od ostatka ekonomije .
U svakom slučaju , objavili smo taj izvještaj u julu prošle godine .
Državna televizija našla se pod zabranom emitovanja pet minuta prije samog emitovanja . Kao iz filma , zabrana se našla na novinarskom stolu , i voditelj je rekao , &quot; Ovo se nikad prije nije desilo . Šta da radimo ? &quot;
Stoga smo prikazivali samo internet-stranicu , čitavo vrijeme , kao pokriće . I postali smo vrlo poznati na Islandu , otišli smo tamo i govorili o ovom problemu .
Pojavio se osjećaj u zajednici da se to nikad ne smije ponoviti . Kao rezultat , kroz rad sa nekim islandskim političarima i nekim drugim međunarodnim pravnim stručnjacima , došli smo do nekog novog paketa propisa za Island da bi na neki način postalo spoljašnje utočište za slobodno novinarstvo , sa najjačom zaštitom novinara u svijetu , sa novom Nobelovom nagradom za slobodu govora .
Island je nordijska zemlja pa je poput Norveške , u stanju da to unese u sistem .
Baš prije mjesec dana , ovo je prošlo jednoglasno od strane islandskog parlamenta .
KA : Opa .
( Aplauz ) Zadnje pitanje za vas , Julijan .
Kada razmišljate o budućnosti , da li mislite da će vjerovatno Veliki Brat imati više kontrole , više tajnovitosti , ili mi koji gledamo Velikog Brata , ili će se sve to odigrati na bilo koji način ?
JA : Nisam baš siguran u kojem pravcu to ide .
Mislim , postoje ogromni pritisci da se izjednače propisi slobode govora i propisi o transparentnosti širom svijeta — unutar Evropske Unije , između Kine i SAD-a .
Kojim putem će to krenuti ? Teško je predvidjeti .
Zato je vrlo interesantno biti u ovom vremenu . Jer uz samo manji napor mozemo usmjeriti tok na bilo koju stranu .
KA : Pa mislim , izgleda kao da odražavam mišljenje publike kad kažem , Julijane , budite oprezni i neka je snaga na vašoj strani .
JA : Hvala vam , Kris . ( KA : Hvala vama . ) ( Aplauz )
Zovem se Amit .
Prije 18 mjeseci , radio sam još jedan posao u Google , i spomenuo sam ovu ideju da uradim nešto sa muzejima i umjetnosti mojoj šefici koja je zapravo ovdje , i ona mi je omogućila da to uradim .
Za to mi je trebalo 18 mjeseci .
Mogu vam reći da je bilo dosta zanimljivih pregovora i priča sa 17 veoma interesantnih muzeja iz devet zemalja .
Ali ja ću se fokusirati na demo .
Postoji više priča o tome zašto smo ovo napravili .
Mislim da je moja vlastita priča veoma jednostavno objašnjena na slideu , i to je pristup .
Odrastao sam u Indiji .
Imao sam odlično obrazovanje – ne mogu se požaliti — ali nisam imao pristup većini ovih muzeja i umjetničkih djela .
Tako da kada sam počeo putovati i posjećivati ove muzeje , počeo sam mnogo učiti .
I dok sam radio za Google , pokušao sam usmjeriti tu želju da bude što više pristupačnija uz tehnologiju .
Tako smo formirali tim , odličan tim ljudi , i počeli smo raditi na ovome .
Vjerovatno ću se pozabaviti sa demom i ispričaću vam nekoliko interesantnih stvari sa kojima smo se suočili od lansiranja .
Jednostavno je : posjetite GoogleArtProject.com.
Pogledate sve ove muzeje koji se ovdje nalaze .
Imate Uffizi , imate MoMA , Hermitage , Rijks , Van Gogh .
Zapravo ću doći do mog najomiljenijeg , to je Metropolitan muzej umjetnosti u New Yorku .
Postoje dva načina za ulaz – veoma je jednostavno .
Kliknite i , bum , nalazite se u ovom muzeju .
Nije važno gdje ste — Bombaj , Meksiko , zaista nije važno .
Krećete se okolo , zabavljate se .
Želite upravljati muzejom ?
Otvorite plan , i jednim klikom , skočite .
Unutra ste i želite ići na kraj hodnika .
Nastavite . Zabavite se .
Istražujte .
( Aplauz ) Hvala vam . Još nisam došao do najboljeg dijela .
( Smijeh ) Sada sam ispred jedne od mojih omiljenih slika , Harvesters od Pieter Breugela u Metu .
Vidim ovaj znak plus .
Ukoliko vam je muzej dao sliku , kliknite na nju .
Ovo je sada jedna od slika .
Prema tome , ovo su svi meta podaci .
Za one koje zaista zanima umjetnost , možete kliknuti na ovo – ali ću ja kliknuti na ovo sada .
I ovo je jedna od slika koje smo uhvatili onim što zovemo gigapiksel tehnologijom .
Tako da ova slika , na primjer , ima približno , mislim , oko 10 milijardi piksela .
I dosta me ljudi pita : &quot; Šta dobijete za tih 10 milijardi piksela ? &quot;
Tako da ću vam sada pokušati pokazati šta zaista dobijem za 10 milijardi piksela .
Možete povećati sliku veoma jednostavno .
Vidite da se ovdje dešavaju neke zabavne stvari .
Volim ovog čovjeka ; njegov izraz lica je neprocjenjiv .
Ali tada zaista želite ići dalje .
I tako sam počeo da se igram , i otkrio sam da se ovdje nešto dešava .
I bio sam poput , &quot; &quot; Čekaj . To zvuči interesantno . &quot; &quot; Ušao sam i počeo primjećivati da ova djeca zapravo udaraju nešto .
Malo sam istraživao , razgovarao sa nekoliko poznanika u Metu , i zapravo sam otkrio da je ovo igra koja se zove bacanje , koja uključuje udaranje guske sa štapom na dan palačinaka .
I očigledno je bila dosta popularna .
Ne znam zašto su to uradili , ali sam naučio nešto o tome .
Da se sada zaista koncentrišemo , možete zaista vidjeti pukotine .
Samo da vam dam neku perspektivu , Povećaću je kako biste zaista vidjeli šta ćete dobiti .
Bili smo ovdje , a ovo je slika .
( Aplauz ) Najbolje tek dolazi – za koji trenutak .
Hajdemo sada brzo preći na MoMA , također u New Yorku .
Jedna od mojih omiljenih , Zvjezdana noć . Primjer koji sam vam pokazao je bio o pronalasku detalja .
Ali šta ako želite da vidite poteze kistom ?
I šta ako želite vidjeti kako je Van Gogh zapravo kreirao svoje remek djelo ?
Povećate je . Zaista dobro pogledate .
Sada ću opisati jedan od najomiljenijih dijelova ove slike , i zaista ću ići do pukotina .
Ovo je Zvjezdana noć , Mislim , kako nikad nije viđena .
Pokazaću vam ostale omiljene karakteristike .
Postoji dosta drugih stvari ovdje , ali nemam vremena .
Ovo je zaista super dio . Zove se Kolekcije .
Bilo ko od vas , bilo ko — neovisno da li ste bogati , siromašni , da li imate otmnjenu kuću – nije važno .
Možete krenuti i kreirati vlastiti muzej putem interneta kreirati vlastitu kolekciju kroz sve ove slike .
Veoma je jednostavno , uđete — i ja sam ovo kreirao pod nazivom Moć povećavanja — možete samo povećavati .
Ovo je slika Ambasadori , koja se nalazi u Nacionalnoj galeriji .
Možete protumačiti djela , poslati ih svojim prijateljima i zaista započeti razgovor o onome šta osjećate kada pregledate ova remek djela .
Kao zaključak , ja smatram da je za mene glavna stvar da sve izvanredne stvari ovdje zaista ne potiču od Google-a .
Po mom mišljenju , one čak i ne potiču iz muzeja .
Vjerovatno to ne bih trebao reći .
One zaista potiču od ovih umjetnika .
I to je bilo moje skromno iskustvo u ovome .
Ja mislim , odnosno , nadam se da u ovom digialnom mediju ne sudimo o njihovom umjetničkom radu te da ih pravilno predstavljamo na internetu .
I najveće pitanje koje mi se postavlja danas jeste , &quot; &quot; Da li sve ovo radite da udvostručite iskustvo odlaska u muzej ? &quot; &quot; Odgovor je ne .
Već kako bi se nadopunio doživljaj .
I to je to . Hvala vam .
( Aplauz ) Hvala vam . ( Aplauz )
Ja sam pripovjedačica .
Na ovom dijapozitivu možemo vidjeti godine na horizontalnoj osi .
Nakon puberteta , nema nas više na ovoj mapi .
Ona ima šest mjeseci .
( Aplauz )
